export const FETCHING_MEMBER = 'FETCHING_MEMBER'
export const FETCHING_MEMBER_SUCCESS = 'FETCHING_MEMBER_SUCCESS'
export const FETCHING_MEMBER_FAILURE = 'FETCHING_MEMBER_FAILURE'
export const ADD_MEMBER = 'ADD_MEMBER';
export const EDIT_MEMBER = 'EDIT_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
